import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import styled from "styled-components";
import { Team } from "../types/types";
import TeamComponent from "../components/Team";
import CardComponent from "../components/Card";

const Home: NextPage = () => {
  const mockTeam: Team = {
    members: [{ name: "Mohammad" }, { name: "Hussein" }],
  };
  const mockTeam2: Team = {
    members: [{ name: "Ahamad" }, { name: "Alvina" }],
  };

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HUD>
        <TimerContainer>
          <p>1:30</p>
        </TimerContainer>
      </HUD>

      <ContentContainer>
        <TeamComponent team={mockTeam} />
        <MainContainer></MainContainer>

        <TeamComponent team={mockTeam2} />
      </ContentContainer>
    </Container>
  );
};

const Container = styled.div``;

const HUD = styled.div`
  display: flex;
  justify-content: center;
`;

const TimerContainer = styled.div``;

const ContentContainer = styled.div`
  display: flex;
  justify-content: space-between;
`;

const MainContainer = styled.div`
  background-color: green;
  flex-grow: 1;
  display: flex;
  justify-content: center;
`;

export default Home;
