import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useState } from "react";
import styled from "styled-components";
import { Card, Team } from "../types/types";
import TeamComponent from "../components/Team";
import CardComponent from "../components/Card";
import useRoom from "../hooks/useRoom";

const Home: NextPage = () => {
  const { room } = useRoom();

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HUD>
        <TimerContainer>
          <p>1:30</p>
        </TimerContainer>
      </HUD>

      <ContentContainer>
        <TeamComponent team={room?.teams[0]} />
        <MainContainer>
          <CardComponent card={room?.currentCard} onCorrect={() => {}} onTaboo={() => alert("bye")} />
        </MainContainer>
        <TeamComponent team={room?.teams[1]} />
      </ContentContainer>
    </Container>
  );
};

const Container = styled.div``;

const HUD = styled.div`
  display: flex;
  justify-content: center;
`;

const TimerContainer = styled.div``;

const ContentContainer = styled.div`
  display: flex;
  justify-content: space-between;
`;

const MainContainer = styled.div`
  background-color: green;
  flex-grow: 1;
  display: flex;
  justify-content: center;
`;

export default Home;
